# Generated by Django 3.1.4 on 2020-12-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'hierarchies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('path', models.CharField(blank=True,
                                          db_index=True, editable=False, max_length=300)),
                ('slug_path', models.CharField(blank=True,
                                               db_index=True, editable=False, max_length=300)),
                ('featured', models.BooleanField(default=False)),
                ('hierarchy', models.ForeignKey(blank=True, help_text='Must be explicitly selected if there is no parent category.',
                                                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='fragment_categories.hierarchy')),
                ('parent', models.ForeignKey(blank=True, help_text='If not defined, this will be a top-level category in the given hierarchy.', null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fragment_categories.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('path',),
                'unique_together': {('parent', 'name')},
            },
        ),
    ]
